export const statesWithDistricts = [
  {
    state: "Bihar",
    districts: [
      {
        name: "Vaishali",
        blocks: [
          // { name: "bhagwanpur", villages: [] },
          // { name: "Bidupur", villages: [] },
          // { name: "Chehra Kalan", villages: [] },
          // { name: "Desri", villages: [] },
          // { name: "Goraul", villages: [] },
          // { name: "Hajipur", villages: [] },
          // { name: "Jandaha", villages: [] },
          // { name: "Lalganj", villages: [] },
          // { name: "Mahnar", villages: [] },
          {
            name: "Raghopur",
            villages: [
              "Ashpatpur Singhia Urf Latiahi",
              "Ashpatpursinghia Urf Bariarpur",
              "Bahrampur",
              "Bhawani Prasad Urf Madho",
              "Birpur",
              "Bishunpur Maniari",
              "Chak Basant",
              "Chak Chand",
              "Chak Khetal",
              "Chak Mahabal",
              "Chak Narayan",
              "Chak Singar Barari",
              "Chak Singar Karari",
              "Chak Thakru",
              "Chandpur Idark",
              "Chaunkia",
              "Dwarkapur",
              "Etwarpur",
              "Fatehpur Shahbaz",
              "Gobardhanpur",
              "Gorari",
              "Haibatpur Barari",
              "Haibatpur Karari",
              "Hajpurwa",
              "Himatpur Diara",
              "Ibrahimabad",
              "Ismailpur",
              "Jafrabad Dih",
              "Jafrabadtok Arazibeshinaobarar",
              "Jagdishpur Idrakarai Barari",
              "Jahangirpur Phuli",
              "Jahangirpur Pirthi",
              "Jamalpur Chak Shankerganga Pra",
              "Jethuli",
              "Juramanpur Barari",
              "Juramanpur Karari",
              "Juramanpur Taufir",
              "Karmupur",
              "Maheshpur",
              "Malikpur",
              "Mirampur Alakh Deori",
              "Mirzapur Lachhu",
              "Mohanpur",
              "Mokrampur",
              "Nagargawan",
              "Paharpur",
              "Panapur Pakauli",
              "Paroha",
              "Parsotimpur",
              "Parsotimpur Barari",
              "Pirmohammadpur",
              "Raghopur",
              "Ramdauli Barari",
              "Rampur Karari Barari",
              "Rampur Shamchand",
              "Rustampur",
              "Saidabad",
              "Saidpur Deochand",
              "Saidpur Hulas",
              "Saidpur Singhia",
              "Saifabad",
              "Shaistapur",
              "Shiuprasad Motaluke Gobindpur",
              "Sirirampur",
              "Sorabpur Urf Saraepur",
              "Sukwarpur",
              "Terahrasia",
              "Wahidpur",
            ],
          },
          // { name: "Patepur", villages: [] },
          // { name: "Sahdei Buzurg", villages: [] },
          // { name: "Rajapakar", villages: [] },
          // { name: "sarai", villages: [] },
        ],
      },
      // { name: "Araria", blocks: [] },
      // { name: "Arwal", blocks: [] },
      // { name: "Aurangabad", blocks: [] },
      // { name: "Banka", blocks: [] },
      // { name: "Begusarai", blocks: [] },
      // { name: "Bhagalpur", blocks: [] },
      // { name: "Bhojpur", blocks: [] },
      // { name: "Buxar", blocks: [] },
      // { name: "Darbhanga", blocks: [] },
      // { name: "East Champaran", blocks: [] },
      // { name: "Gaya", blocks: [] },
      // { name: "Gopalganj", blocks: [] },
      // { name: "Jamui", blocks: [] },
      // { name: "Jehanabad", blocks: [] },
      // { name: "Kaimur", blocks: [] },
      // { name: "Katihar", blocks: [] },
      // { name: "Khagaria", blocks: [] },
      // { name: "Kishanganj", blocks: [] },
      // { name: "Lakhisarai", blocks: [] },
      // { name: "Madhepura", blocks: [] },
      // { name: "Madhubani", blocks: [] },
      // { name: "Munger", blocks: [] },
      // { name: "Muzaffarpur", blocks: [] },
      // { name: "Nalanda", blocks: [] },
      // { name: "Nawada", blocks: [] },
      // { name: "Patna", blocks: [] },
      // { name: "Purnia", blocks: [] },
      // { name: "Rohtas", blocks: [] },
      // { name: "Saharsa", blocks: [] },
      // { name: "Samastipur", blocks: [] },
      // { name: "Saran", blocks: [] },
      // { name: "Sheikhpura", blocks: [] },
      // { name: "Sheohar", blocks: [] },
      // { name: "Sitamarhi", blocks: [] },
      // { name: "Siwan", blocks: [] },
      // { name: "Supaul", blocks: [] },
      // { name: "West Champaran", blocks: [] },
    ],
  },
  // {
  //   state: "Andhra Pradesh",
  //   districts: [
  //     "Alluri Sitharama Raju",
  //     "Anakapalli",
  //     "Ananthapuramu",
  //     "Annamayya",
  //     "Bapatla",
  //     "Chittoor",
  //     "Dr. B.R. Ambedkar Konaseema",
  //     "East Godavari",
  //     "Eluru",
  //     "Guntur",
  //     "Kakinada",
  //     "Krishna",
  //     "Kurnool",
  //     "Nandyal",
  //     "NTR",
  //     "Palnadu",
  //     "Parvathipuram Manyam",
  //     "Prakasam",
  //     "Srikakulam",
  //     "Sri Potti Sriramulu Nellore",
  //     "Sri Sathya Sai",
  //     "Tirupati",
  //     "Visakhapatnam",
  //     "Vizianagaram",
  //     "West Godavari",
  //     "YSR Kadapa",
  //   ],
  // },
  // {
  //   state: "Arunachal Pradesh",
  //   districts: [
  //     "Anjaw",
  //     "Changlang",
  //     "Dibang Valley",
  //     "East Kameng",
  //     "East Siang",
  //     "Kamle",
  //     "Kra Daadi",
  //     "Kurung Kumey",
  //     "Lepa Rada",
  //     "Lohit",
  //     "Longding",
  //     "Lower Dibang Valley",
  //     "Lower Siang",
  //     "Lower Subansiri",
  //     "Namsai",
  //     "Pakke-Kessang",
  //     "Papum Pare",
  //     "Shi Yomi",
  //     "Siang",
  //     "Tawang",
  //     "Tirap",
  //     "Upper Siang",
  //     "Upper Subansiri",
  //     "West Kameng",
  //     "West Siang",
  //   ],
  // },
  // {
  //   state: "Assam",
  //   districts: [
  //     "Baksa",
  //     "Barpeta",
  //     "Biswanath",
  //     "Bongaigaon",
  //     "Cachar",
  //     "Charaideo",
  //     "Chirang",
  //     "Darrang",
  //     "Dhemaji",
  //     "Dhubri",
  //     "Dibrugarh",
  //     "Dima Hasao",
  //     "Goalpara",
  //     "Golaghat",
  //     "Hailakandi",
  //     "Hojai",
  //     "Jorhat",
  //     "Kamrup",
  //     "Kamrup Metropolitan",
  //     "Karbi Anglong",
  //     "Karimganj",
  //     "Kokrajhar",
  //     "Lakhimpur",
  //     "Majuli",
  //     "Morigaon",
  //     "Nagaon",
  //     "Nalbari",
  //     "Sivasagar",
  //     "Sonitpur",
  //     "South Salmara-Mankachar",
  //     "Tinsukia",
  //     "Udalguri",
  //     "West Karbi Anglong",
  //   ],
  // },
  // {
  //   state: "Chhattisgarh",
  //   districts: [
  //     "Balod",
  //     "Baloda Bazar",
  //     "Balrampur",
  //     "Bastar",
  //     "Bemetara",
  //     "Bijapur",
  //     "Bilaspur",
  //     "Dantewada",
  //     "Dhamtari",
  //     "Durg",
  //     "Gariaband",
  //     "Gaurella-Pendra-Marwahi",
  //     "Janjgir-Champa",
  //     "Jashpur",
  //     "Kabirdham",
  //     "Kanker",
  //     "Kondagaon",
  //     "Korba",
  //     "Koriya",
  //     "Mahasamund",
  //     "Mungeli",
  //     "Narayanpur",
  //     "Raigarh",
  //     "Raipur",
  //     "Rajnandgaon",
  //     "Sukma",
  //     "Surajpur",
  //     "Surguja",
  //   ],
  // },
  // { state: "Goa", districts: ["North Goa", "South Goa"] },
  // {
  //   state: "Gujarat",
  //   districts: [
  //     "Ahmedabad",
  //     "Amreli",
  //     "Anand",
  //     "Aravalli",
  //     "Banaskantha",
  //     "Bharuch",
  //     "Bhavnagar",
  //     "Botad",
  //     "Chhota Udaipur",
  //     "Dahod",
  //     "Dang",
  //     "Devbhoomi Dwarka",
  //     "Gandhinagar",
  //     "Gir Somnath",
  //     "Jamnagar",
  //     "Junagadh",
  //     "Kheda",
  //     "Kutch",
  //     "Mahisagar",
  //     "Mehsana",
  //     "Morbi",
  //     "Narmada",
  //     "Navsari",
  //     "Panchmahal",
  //     "Patan",
  //     "Porbandar",
  //     "Rajkot",
  //     "Sabarkantha",
  //     "Surat",
  //     "Surendranagar",
  //     "Tapi",
  //     "Vadodara",
  //     "Valsad",
  //   ],
  // },
  // {
  //   state: "Haryana",
  //   districts: [
  //     "Ambala",
  //     "Bhiwani",
  //     "Charkhi Dadri",
  //     "Faridabad",
  //     "Fatehabad",
  //     "Gurugram",
  //     "Hisar",
  //     "Jhajjar",
  //     "Jind",
  //     "Kaithal",
  //     "Karnal",
  //     "Kurukshetra",
  //     "Mahendragarh",
  //     "Nuh",
  //     "Palwal",
  //     "Panchkula",
  //     "Panipat",
  //     "Rewari",
  //     "Rohtak",
  //     "Sirsa",
  //     "Sonipat",
  //     "Yamunanagar",
  //   ],
  // },
  // {
  //   state: "Himachal Pradesh",
  //   districts: [
  //     "Bilaspur",
  //     "Chamba",
  //     "Hamirpur",
  //     "Kangra",
  //     "Kinnaur",
  //     "Kullu",
  //     "Lahaul and Spiti",
  //     "Mandi",
  //     "Shimla",
  //     "Sirmaur",
  //     "Solan",
  //     "Una",
  //   ],
  // },
  // {
  //   state: "Jharkhand",
  //   districts: [
  //     "Bokaro",
  //     "Chatra",
  //     "Deoghar",
  //     "Dhanbad",
  //     "Dumka",
  //     "East Singhbhum",
  //     "Garhwa",
  //     "Giridih",
  //     "Godda",
  //     "Gumla",
  //     "Hazaribagh",
  //     "Jamtara",
  //     "Khunti",
  //     "Koderma",
  //     "Latehar",
  //     "Lohardaga",
  //     "Pakur",
  //     "Palamu",
  //     "Ramgarh",
  //     "Ranchi",
  //     "Sahibganj",
  //     "Seraikela Kharsawan",
  //     "Simdega",
  //     "West Singhbhum",
  //   ],
  // },
  // {
  //   state: "Karnataka",
  //   districts: [
  //     "Bagalkot",
  //     "Ballari",
  //     "Belagavi",
  //     "Bengaluru Rural",
  //     "Bengaluru Urban",
  //     "Bidar",
  //     "Chamarajanagar",
  //     "Chikballapur",
  //     "Chikkamagaluru",
  //     "Chitradurga",
  //     "Dakshina Kannada",
  //     "Davanagere",
  //     "Dharwad",
  //     "Gadag",
  //     "Hassan",
  //     "Haveri",
  //     "Kalaburagi",
  //     "Kodagu",
  //     "Kolar",
  //     "Koppal",
  //     "Mandya",
  //     "Mysuru",
  //     "Raichur",
  //     "Ramanagara",
  //     "Shivamogga",
  //     "Tumakuru",
  //     "Udupi",
  //     "Uttara Kannada",
  //     "Vijayapura",
  //     "Yadgir",
  //   ],
  // },
  // {
  //   state: "Kerala",
  //   districts: [
  //     "Alappuzha",
  //     "Ernakulam",
  //     "Idukki",
  //     "Kannur",
  //     "Kasaragod",
  //     "Kollam",
  //     "Kottayam",
  //     "Kozhikode",
  //     "Malappuram",
  //     "Palakkad",
  //     "Pathanamthitta",
  //     "Thiruvananthapuram",
  //     "Thrissur",
  //     "Wayanad",
  //   ],
  // },
  // {
  //   state: "Madhya Pradesh",
  //   districts: [
  //     "Agar Malwa",
  //     "Alirajpur",
  //     "Anuppur",
  //     "Ashoknagar",
  //     "Balaghat",
  //     "Barwani",
  //     "Betul",
  //     "Bhind",
  //     "Bhopal",
  //     "Burhanpur",
  //     "Chhatarpur",
  //     "Chhindwara",
  //     "Damoh",
  //     "Datia",
  //     "Dewas",
  //     "Dhar",
  //     "Dindori",
  //     "Guna",
  //     "Gwalior",
  //     "Harda",
  //     "Hoshangabad",
  //     "Indore",
  //     "Jabalpur",
  //     "Jhabua",
  //     "Katni",
  //     "Khandwa",
  //     "Khargone",
  //     "Mandla",
  //     "Mandsaur",
  //     "Morena",
  //     "Narsinghpur",
  //     "Neemuch",
  //     "Niwari",
  //     "Panna",
  //     "Raisen",
  //     "Rajgarh",
  //     "Ratlam",
  //     "Rewa",
  //     "Sagar",
  //     "Satna",
  //     "Sehore",
  //     "Seoni",
  //     "Shahdol",
  //     "Shajapur",
  //     "Sheopur",
  //     "Shivpuri",
  //     "Sidhi",
  //     "Singrauli",
  //     "Tikamgarh",
  //     "Ujjain",
  //     "Umaria",
  //     "Vidisha",
  //   ],
  // },
  // {
  //   state: "Maharashtra",
  //   districts: [
  //     "Ahmednagar",
  //     "Akola",
  //     "Amravati",
  //     "Aurangabad",
  //     "Beed",
  //     "Bhandara",
  //     "Buldhana",
  //     "Chandrapur",
  //     "Dhule",
  //     "Gadchiroli",
  //     "Gondia",
  //     "Hingoli",
  //     "Jalgaon",
  //     "Jalna",
  //     "Kolhapur",
  //     "Latur",
  //     "Mumbai City",
  //     "Mumbai Suburban",
  //     "Nagpur",
  //     "Nanded",
  //     "Nandurbar",
  //     "Nashik",
  //     "Osmanabad",
  //     "Palghar",
  //     "Parbhani",
  //     "Pune",
  //     "Raigad",
  //     "Ratnagiri",
  //     "Sangli",
  //     "Satara",
  //     "Sindhudurg",
  //     "Solapur",
  //     "Thane",
  //     "Wardha",
  //     "Washim",
  //     "Yavatmal",
  //   ],
  // },
  // {
  //   state: "Manipur",
  //   districts: [
  //     "Bishnupur",
  //     "Chandel",
  //     "Churachandpur",
  //     "Imphal East",
  //     "Imphal West",
  //     "Jiribam",
  //     "Kakching",
  //     "Kamjong",
  //     "Kangpokpi",
  //     "Noney",
  //     "Pherzawl",
  //     "Senapati",
  //     "Tamenglong",
  //     "Tengnoupal",
  //     "Thoubal",
  //     "Ukhrul",
  //   ],
  // },
  // {
  //   state: "Meghalaya",
  //   districts: [
  //     "East Garo Hills",
  //     "East Jaintia Hills",
  //     "East Khasi Hills",
  //     "North Garo Hills",
  //     "Ri Bhoi",
  //     "South Garo Hills",
  //     "South West Garo Hills",
  //     "South West Khasi Hills",
  //     "West Garo Hills",
  //     "West Jaintia Hills",
  //     "West Khasi Hills",
  //   ],
  // },
  // {
  //   state: "Mizoram",
  //   districts: [
  //     "Aizawl",
  //     "Champhai",
  //     "Hnahthial",
  //     "Khawzawl",
  //     "Kolasib",
  //     "Lawngtlai",
  //     "Lunglei",
  //     "Mamit",
  //     "Saitual",
  //     "Serchhip",
  //   ],
  // },
  // {
  //   state: "Nagaland",
  //   districts: [
  //     "Chümoukedima",
  //     "Dimapur",
  //     "Kiphire",
  //     "Kohima",
  //     "Longleng",
  //     "Mokokchung",
  //     "Mon",
  //     "Niuland",
  //     "Noklak",
  //     "Peren",
  //     "Phek",
  //     "Shamator",
  //     "Tseminyü",
  //     "Tuensang",
  //     "Wokha",
  //     "Zünheboto",
  //   ],
  // },
  // {
  //   state: "Odisha",
  //   districts: [
  //     "Angul",
  //     "Balangir",
  //     "Balasore",
  //     "Bargarh",
  //     "Bhadrak",
  //     "Boudh",
  //     "Cuttack",
  //     "Deogarh",
  //     "Dhenkanal",
  //     "Gajapati",
  //     "Ganjam",
  //     "Jagatsinghpur",
  //     "Jajpur",
  //     "Jharsuguda",
  //     "Kalahandi",
  //     "Kandhamal",
  //     "Kendrapara",
  //     "Kendujhar (Keonjhar)",
  //     "Khordha",
  //     "Koraput",
  //     "Malkangiri",
  //     "Mayurbhanj",
  //     "Nabarangpur",
  //     "Nayagarh",
  //     "Nuapada",
  //     "Puri",
  //     "Rayagada",
  //     "Sambalpur",
  //     "Sonepur",
  //     "Sundargarh",
  //   ],
  // },
  // {
  //   state: "Punjab",
  //   districts: [
  //     "Amritsar",
  //     "Barnala",
  //     "Bathinda",
  //     "Faridkot",
  //     "Fatehgarh Sahib",
  //     "Fazilka",
  //     "Ferozepur",
  //     "Gurdaspur",
  //     "Hoshiarpur",
  //     "Jalandhar",
  //     "Kapurthala",
  //     "Ludhiana",
  //     "Malerkotla",
  //     "Mansa",
  //     "Moga",
  //     "Muktsar",
  //     "Nawanshahr (Shaheed Bhagat Singh Nagar)",
  //     "Pathankot",
  //     "Patiala",
  //     "Rupnagar",
  //     "Sangrur",
  //     "SAS Nagar (Mohali)",
  //     "Tarn Taran",
  //   ],
  // },
  // {
  //   state: "Rajasthan",
  //   districts: [
  //     "Ajmer",
  //     "Alwar",
  //     "Anupgarh",
  //     "Balotra",
  //     "Banswara",
  //     "Baran",
  //     "Barmer",
  //     "Beawar",
  //     "Bharatpur",
  //     "Bhilwara",
  //     "Bikaner",
  //     "Bundi",
  //     "Chittorgarh",
  //     "Churu",
  //     "Dausa",
  //     "Dholpur",
  //     "Didwana-Kuchaman",
  //     "Dungarpur",
  //     "Hanumangarh",
  //     "Jaipur",
  //     "Jaisalmer",
  //     "Jalore",
  //     "Jhalawar",
  //     "Jhunjhunu",
  //     "Jodhpur",
  //     "Karauli",
  //     "Kekri",
  //     "Kota",
  //     "Nagaur",
  //     "Neem Ka Thana",
  //     "Pali",
  //     "Phalodi",
  //     "Pratapgarh",
  //     "Rajsamand",
  //     "Salumbar",
  //     "Sanchore",
  //     "Sawai Madhopur",
  //     "Sikar",
  //     "Sirohi",
  //     "Sri Ganganagar",
  //     "Sri Madhopur",
  //     "Tonk",
  //     "Udaipur",
  //   ],
  // },
  // {
  //   state: "Sikkim",
  //   districts: [
  //     "Gangtok",
  //     "Gyalshing",
  //     "Mangan",
  //     "Namchi",
  //     "Pakyong",
  //     "Soreng",
  //     "Tadong",
  //     "Yangang",
  //   ],
  // },
  // {
  //   state: "Tamil Nadu",
  //   districts: [
  //     "Ariyalur",
  //     "Chengalpattu",
  //     "Chennai",
  //     "Coimbatore",
  //     "Cuddalore",
  //     "Dharmapuri",
  //     "Dindigul",
  //     "Erode",
  //     "Kallakurichi",
  //     "Kanchipuram",
  //     "Kanyakumari",
  //     "Karur",
  //     "Krishnagiri",
  //     "Madurai",
  //     "Nagapattinam",
  //     "Namakkal",
  //     "Nilgiris",
  //     "Perambalur",
  //     "Pudukkottai",
  //     "Ramanathapuram",
  //     "Ranipet",
  //     "Salem",
  //     "Sivaganga",
  //     "Tenkasi",
  //     "Thanjavur",
  //     "Theni",
  //     "Thoothukudi",
  //     "Tiruchirappalli",
  //     "Tirunelveli",
  //     "Tirupathur",
  //     "Tiruppur",
  //     "Tiruvallur",
  //     "Tiruvannamalai",
  //     "Tiruvarur",
  //     "Vellore",
  //     "Viluppuram",
  //     "Virudhunagar",
  //   ],
  // },
  // {
  //   state: "Telangana",
  //   districts: [
  //     "Adilabad",
  //     "Bhadradri Kothagudem",
  //     "Hanamkonda",
  //     "Hyderabad",
  //     "Jagtial",
  //     "Jangaon",
  //     "Jayashankar Bhupalapally",
  //     "Jogulamba Gadwal",
  //     "Kamareddy",
  //     "Karimnagar",
  //     "Khammam",
  //     "Komaram Bheem",
  //     "Mahabubabad",
  //     "Mahabubnagar",
  //     "Mancherial",
  //     "Medak",
  //     "Medchal–Malkajgiri",
  //     "Mulugu",
  //     "Nagarkurnool",
  //     "Nalgonda",
  //     "Narayanpet",
  //     "Nirmal",
  //     "Nizamabad",
  //     "Peddapalli",
  //     "Rajanna Sircilla",
  //     "Ranga Reddy",
  //     "Sangareddy",
  //     "Siddipet",
  //     "Suryapet",
  //     "Vikarabad",
  //     "Wanaparthy",
  //     "Warangal",
  //     "Yadadri Bhuvanagiri",
  //   ],
  // },
  // {
  //   state: "Tripura",
  //   districts: [
  //     "Dhalai",
  //     "Gomati",
  //     "Khowai",
  //     "North Tripura",
  //     "Sepahijala",
  //     "South Tripura",
  //     "Unakoti",
  //     "West Tripura",
  //   ],
  // },
  // {
  //   state: "Uttar Pradesh",
  //   districts: [
  //     "Agra",
  //     "Aligarh",
  //     "Ambedkar Nagar",
  //     "Amethi",
  //     "Amroha",
  //     "Auraiya",
  //     "Ayodhya",
  //     "Azamgarh",
  //     "Baghpat",
  //     "Bahraich",
  //     "Ballia",
  //     "Balrampur",
  //     "Banda",
  //     "Barabanki",
  //     "Bareilly",
  //     "Basti",
  //     "Bhadohi",
  //     "Bijnor",
  //     "Budaun",
  //     "Bulandshahr",
  //     "Chandauli",
  //     "Chitrakoot",
  //     "Deoria",
  //     "Etah",
  //     "Etawah",
  //     "Farrukhabad",
  //     "Fatehpur",
  //     "Firozabad",
  //     "Gautam Buddha Nagar",
  //     "Ghaziabad",
  //     "Ghazipur",
  //     "Gonda",
  //     "Gorakhpur",
  //     "Hamirpur",
  //     "Hapur",
  //     "Hardoi",
  //     "Hathras",
  //     "Jalaun",
  //     "Jaunpur",
  //     "Jhansi",
  //     "Kannauj",
  //     "Kanpur Dehat",
  //     "Kanpur Nagar",
  //     "Kasganj",
  //     "Kaushambi",
  //     "Kushinagar",
  //     "Lakhimpur Kheri",
  //     "Lalitpur",
  //     "Lucknow",
  //     "Maharajganj",
  //     "Mahoba",
  //     "Mainpuri",
  //     "Mathura",
  //     "Mau",
  //     "Meerut",
  //     "Mirzapur",
  //     "Moradabad",
  //     "Muzaffarnagar",
  //     "Pilibhit",
  //     "Pratapgarh",
  //     "Prayagraj",
  //     "Raebareli",
  //     "Rampur",
  //     "Saharanpur",
  //     "Sambhal",
  //     "Sant Kabir Nagar",
  //     "Shahjahanpur",
  //     "Shamli",
  //     "Sharavasti",
  //     "Siddharthnagar",
  //     "Sitapur",
  //     "Sonbhadra",
  //     "Sultanpur",
  //     "Unnao",
  //     "Varanasi",
  //   ],
  // },
  // {
  //   state: "Uttarakhand",
  //   districts: [
  //     "Almora",
  //     "Bageshwar",
  //     "Chamoli",
  //     "Champawat",
  //     "Dehradun",
  //     "Haridwar",
  //     "Nainital",
  //     "Pauri Garhwal",
  //     "Pithoragarh",
  //     "Rudraprayag",
  //     "Tehri Garhwal",
  //     "Udham Singh Nagar",
  //     "Uttarkashi",
  //   ],
  // },
  // {
  //   state: "West Bengal",
  //   districts: [
  //     "Alipurduar",
  //     "Bankura",
  //     "Birbhum",
  //     "Cooch Behar",
  //     "Dakshin Dinajpur",
  //     "Darjeeling",
  //     "Hooghly",
  //     "Howrah",
  //     "Jalpaiguri",
  //     "Jhargram",
  //     "Kalimpong",
  //     "Kolkata",
  //     "Malda",
  //     "Murshidabad",
  //     "Nadia",
  //     "North 24 Parganas",
  //     "Paschim Bardhaman",
  //     "Paschim Medinipur",
  //     "Purba Bardhaman",
  //     "Purba Medinipur",
  //     "Purulia",
  //     "South 24 Parganas",
  //     "Uttar Dinajpur",
  //   ],
  // },
  // {
  //   state: "Andaman and Nicobar Islands",
  //   districts: ["Nicobar", "North and Middle Andaman", "South Andaman"],
  // },
  // { state: "Chandigarh", districts: ["Chandigarh"] },
  // {
  //   state: "Dadra and Nagar Haveli and Daman and Diu",
  //   districts: ["Dadra and Nagar Haveli", "Daman", "Diu"],
  // },
  // {
  //   state: "Delhi",
  //   districts: [
  //     "Central Delhi",
  //     "East Delhi",
  //     "New Delhi",
  //     "North Delhi",
  //     "North East Delhi",
  //     "North West Delhi",
  //     "Shahdara",
  //     "South Delhi",
  //     "South East Delhi",
  //     "South West Delhi",
  //     "West Delhi",
  //   ],
  // },
  // {
  //   state: "Jammu and Kashmir",
  //   districts: [
  //     "Anantnag",
  //     "Bandipora",
  //     "Baramulla",
  //     "Budgam",
  //     "Doda",
  //     "Ganderbal",
  //     "Jammu",
  //     "Kathua",
  //     "Kishtwar",
  //     "Kulgam",
  //     "Kupwara",
  //     "Poonch",
  //     "Pulwama",
  //     "Rajouri",
  //     "Ramban",
  //     "Reasi",
  //     "Samba",
  //     "Shopian",
  //     "Srinagar",
  //     "Udhampur",
  //   ],
  // },
  // { state: "Ladakh", districts: ["Kargil", "Leh"] },
  // { state: "Lakshadweep", districts: ["Lakshadweep"] },
  // {
  //   state: "Puducherry",
  //   districts: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  // },
];
export const fields = [
  { label: "First name", name: "firstname", type: "text" },
  { label: "Last name", name: "lastname", type: "text" },
  { label: "Mobile", name: "mobile", type: "text" },
  { label: "Email", name: "email", type: "email" },
  { label: "Password", name: "password", type: "password" },
  { label: "Confirm Password", name: "cnfPassword", type: "password" },
];
export const profileEditField = [
  { label: "First Name", name: "firstname", type: "text", isDisable: true },
  { label: "Last Name", name: "lastname", type: "text", isDisable: true },
  { label: "Mobile", name: "mobile", type: "text", isDisable: true },
  { label: "Email", name: "email", type: "email", isDisable: true },
  { label: "School Name", name: "schoolname", type: "text" },
  { label: "School Code", name: "schoolcode", type: "text" },
];
export const teacherCode = [
  "Exclusive Teacher",
  "Bpsc Teacher (School Teacher)",
  "Regular",
];
export const classGroup = [
  { name: "1-5", subjects: ["General (1-5)", "Urdu (1-5)", "Bangla(1 - 5)"] },
  {
    name: "6-8",
    subjects: [
      "English",
      "hindi",
      "math & science",
      "Sanskrit",
      "urdu",
      "physical education",
      "social studies",
    ],
  },
  "9-10",
  "11-12",
];
